### ISSUE TITLE
자동 예매 시작(매크로) - 기능 수정 부탁드립니다.

### ISSUE THREAD

**Issue by wthswngud** [youngjin-k/ktx-macro#4]
안녕하세요.
매크로 관련 문의 드립니다.

현재 자동예약 버튼 및 체크박스가 사라져서
자동 예약 기능을 사용하지 못하고 있습니다.

아마도 ktx홈페이지가 변경된 것에 따른 문제이지 않을까 싶은데
혹시 수정 가능하실까요?

개선이 됐으면 하는 바램입니다.

**Comment by wthswngud** [comment]
매크로 문제 없이 작동 한다고 하셨는데...
저는 안되는데;;
크롬, 네이버 웨일 둘다 확인 해 봤는데
'자동 예약 시작' 버튼 및 체크박스가 생성 되지 않습니다.

두 브라우저 모두 최신 버전 입니다.

캐시 모두 삭제해봤고 매크로 재설치 및 브라우저 재설치
재부팅까지 해봤지만 안되네요;;

**Comment by youngjin-k** [comment]
안녕하세요 @wthswngud 님. 
이슈 제보해주셔서 감사합니다.
letskorail 사이트가 http에서 https로 변경되면서 발생 된 문제이며, (참고 https://github.com/youngjin-k/ktx-macro/pull/5)
현재는 수정이 완료되어 스토어에 심사 요청을 올려둔 상태입니다.
코로나19의 영향으로 심사가 다소 지연될 수 있다고 안내되어 있어, 얼마나 소요될 지는 알 수 없습니다.
사용이 급하신 경우 master 브랜치를 다운로드하셔서, 크롬 확장프로그램 메뉴에서 로드하여 바로 사용하실 수 있습니다.
해당 이슈는 종료하겠습니다.
